---
apiVersion: v1
kind: Secret
metadata:
  name: secret_acess_keys
type: Opaque
stringData:
  SECRET_ACCESS_KEY: |-
    nggXoe8lHbMk2iKzlNwj934chHFgcLLlZY8mvsFi

---
apiVersion: v1
kind: Secret
metadata:
  name: acess_keys
type: Opaque
stringData:
  ACCESS_KEY: |-
    AKIAISLWNKPPEURSIQMA
